# Generated by Django 4.2.5 on 2023-09-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image_url', models.URLField(null=True, verbose_name='Изображение товара')),
                ('discount', models.CharField(max_length=200, verbose_name='Скидка')),
            ],
        ),
    ]
